
<div class="articles">
<div class="card" style="width: 18rem;">
  <img src="img/article1.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Ajouter</a>
  </div>
</div>

<div class="card" style="width: 18rem;">
  <img src="img/article2.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Ajouter</a>
  </div>
</div>

<div class="card" style="width: 18rem;">
  <img src="img/article3.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Ajouter</a>
  </div>
</div>

</div>	




<div class="articles">
<div class="card" style="width: 18rem;">
  <img src="img/article1.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Ajouter</a>
  </div>
</div>

<div class="card" style="width: 18rem;">
  <img src="img/article2.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Ajouter</a>
  </div>
</div>

<div class="card" style="width: 18rem;">
  <img src="img/article3.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Ajouter</a>
  </div>
</div>

</div>	