<div class="card bg-dark text-white">
  <img src="img/statue.jpg" class="card-img" alt="statue">
  <div class="card-img-overlay">
    <h5 class="card-title">This content</h5>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional cotent. This content is a little bit longer.</p>
    <p class="card-text">Last updated 3 mins ago</p>
  </div>
</div>