<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8"/>
    	<title>E-commerce</title>
    	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    	<link rel="stylesheet" type="text/css" href="css/style.css">
	</head>

    <body>

    <nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
      <div class="navbar">
      	<a class="nav-link active" href="index.php?page=homepage">Acceuil</a>
        <a class="nav-link active" href="index.php?page=article">Articles</a>
        <a class="nav-link active" href="index.php?page=connexion">Connexion</a>
        <a class="nav-link active" href="index.php?page=insription">S'inscrire</a>
        <a class="nav-link active" href="#">Panier</a>
      </div>
  </div>
</nav>


  <main>
        <?php require $page ?>
  </main>

    </body>
</html>




